//user
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

//categories
export const LIST_CATEGORY_REQUEST = "LIST_CATEGORY_REQUEST";
export const LIST_CATEGORY_SUCCESS = "LIST_CATEGORY_SUCCESS";
export const LIST_CATEGORY_FAILED = "LIST_CATEGORY_FAILED";

export const GET_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAILED = "GET_CATEGORY_FAILED";

export const ADD_CATEGORY_REQUEST = "ADD_CATEGORY_REQUEST";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILED = "ADD_CATEGORY_FAILED";

export const DELETE_SUBCATEGORY_REQUEST = "DELETE_SUBCATEGORY_REQUEST";
export const DELETE_SUBCATEGORY_SUCCESS = "DELETE_SUBCATEGORY_SUCCESS";
export const DELETE_SUBCATEGORY_FAILED = "DELETE_SUBCATEGORY_FAILED";

export const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILED = "DELETE_CATEGORY_FAILED";

export const GET_SUBCATEGORY_REQUEST = "GET_SUBCATEGORY_REQUEST";
export const GET_SUBCATEGORY_SUCCESS = "GET_SUBCATEGORY_SUCCESS";
export const GET_SUBCATEGORY_FAILED = "GET_SUBCATEGORY_FAILED";

export const EDIT_CATEGORIES_REQUEST = "EDIT_CATEGORIES_REQUEST";
export const EDIT_CATEGORIES_SUCCESS = "EDIT_CATEGORIES_SUCCESS";
export const EDIT_CATEGORIES_FAILED = "EDIT_CATEGORIES_FAILED";

export const EDIT_SUBCATEGORY_REQUEST = "EDIT_SUBCATEGORY_REQUEST";
export const EDIT_SUBCATEGORY_SUCCESS = "EDIT_SUBCATEGORY_SUCCESS";
export const EDIT_SUBCATEGORY_FAILED = "EDIT_SUBCATEGORY_FAILED";
//population
export const LIST_POPULATIONS_REQUEST = "LIST_POPULATIONS_REQUEST";
export const LIST_POPULATIONS_SUCCESS = "LIST_POPULATIONS_SUCCESS";
export const LIST_POPULATIONS_FAILED = "LIST_POPULATIONS_FAILED";
export const ADD_SUBCATEGORY_REQUEST = "ADD_SUBCATEGORY_REQUEST";
export const ADD_SUBCATEGORY_SUCCESS = "ADD_SUBCATEGORY_SUCCESS";
export const ADD_SUBCATEGORY_FAILED = "ADD_SUBCATEGORY_FAILED";

export const DOWNLOAD_EXCEL_REQUEST = "DOWNLOAD_EXCEL_REQUEST";
export const DOWNLOAD_EXCEL_SUCCESS = "DOWNLOAD_EXCEL_SUCCESS";
export const DOWNLOAD_EXCEL_FAILED = "DOWNLOAD_EXCEL_FAILED";
export const LIST_POPULATIONS_MIDDLE_REQUEST =
  "LIST_POPULATIONS_MIDDLE_REQUEST";
export const LIST_POPULATIONS_MIDDLE_SUCCESS =
  "LIST_POPULATIONS_MIDDLE_SUCCESS";
export const LIST_POPULATIONS_MIDDLE_FAILED = "LIST_POPULATIONS_MIDDLE_FAILED";
